if ( GetLocale() == "koKR" ) then

	MARKETWATCHER_ABORT = "취소"
	MARKETWATCHER_ABOVE_THRESHOLD = "한도 이상"
	-- Missing translation
	-- MARKETWATCHER_ACTUAL = "\"Actual\""
	MARKETWATCHER_ADDED_TO_WATCHED = "기록 목록에 추가됨 : [%s]"
	MARKETWATCHER_ADDITEM = "아이템 추가"
	MARKETWATCHER_ADDITEMTEXT = "1. 추적하려는 |cffffff00아이템 이름/ID|r를 입력하세요.\\n2. |cffffff00[정보 가져오기]|r를 누른 후(필요시), |cffffff00[추가]|r를 누르세요.\\n  ※아이템ID는 아래 사이트에서 확인할 수 있습니다.\\n (예1) www.wowhead.com/?item=42225 \\n (예2) thottbot.com/i42225 \\n (예3) wow.inven.co.kr/dataninfo2/item/\\n          detail.php?code=42225"
	MARKETWATCHER_AS_OF_AGO = "%s 전"
	MARKETWATCHER_AUCTIONS_CANCELED = "%i 경매 취소됨"
	MARKETWATCHER_AUDIT = "기록 요약"
	MARKETWATCHER_AUDIT_TEXT = "서버: |cff00ffff%s|r  진영: |cff00ffff%s|r  조사기록 페이지 수: |cff00ffff%i|r"
	MARKETWATCHER_AVERAGE = "\"평균가\""
	MARKETWATCHER_BELOW_THRESHOLD = "한도 이하"
	MARKETWATCHER_BID_PRICE_MARKDOWN = "시작가격 인하"
	MARKETWATCHER_BIDTHRESHOLD = "경매시작가격 한도"
	MARKETWATCHER_BUYOUT_LESS_THAN_BID = "즉시구입가는 경매시작가와 같거나 높아야 합니다."
	MARKETWATCHER_BUYOUT_PRICE_PER_UNIT_ABOVE_THIS_PRICE = "\" 즉시구입 최저가가 아래 설정값보다 높을 때\""
	MARKETWATCHER_BUYOUT_PRICE_PER_UNIT_BELOW_THIS_PRICE = "\" 즉시구입 최저가가 아래 설정값보다 낮을 때\""
	MARKETWATCHER_BUYOUTTHRESHOLD = "즉시구입가격 한도"
	MARKETWATCHER_CANCEL_AUCTIONS = "경매 취소"
	MARKETWATCHER_CANCEL_UNDERCUT = "저가공급 경매 취소"
	MARKETWATCHER_CANCEL_UNDERCUT_CONFIRM_POPUP = "현재 물픔 중 저가공급 물품을 모두 경매 취소하시겠습니까?\\n/n경매를 취소하면 보증금을 잃게됩니다."
	MARKETWATCHER_CONFIG = "MWatcher 옵션"
	MARKETWATCHER_CREATE = "만들기"
	MARKETWATCHER_DEFAULT_UNDERCUT = "즉시구입가격 인하"
	MARKETWATCHER_DELETE_ITEM_POPUP = "추적을 중단하고 현재 아이템에 대한 모든 기록을 삭제하시겠습니까?"
	MARKETWATCHER_DELETE_SCAN_POPUP = "현재 표시된 조사결과 아이템을 삭제하시겠습니까?"
	MARKETWATCHER_DEPOSIT_PAID = "보증금 지불: %s"
	MARKETWATCHER_EDIT = "\"편집 \""
	MARKETWATCHER_EDITITEM = "아이템 편집"
	MARKETWATCHER_EDITSTATUS = "[기록 목록]에 %i 페이지의 조사 기록이 있습니다."
	-- Missing translation
	-- MARKETWATCHER_EMA = "\"EMA\""
	MARKETWATCHER_ENTIRE_HISTORY = "\"전체 기간\""
	MARKETWATCHER_FILTERS_FRAME_TEXT = "아래 항목에 해당하는 아이템을 표시하지 않음"
	MARKETWATCHER_FULLSTACKAUCTIONS = "▶ 최대묶음 경매건수: |cff00ffff%i|r\\n"
	MARKETWATCHER_GEM = "보석"
	MARKETWATCHER_GETITEMINFO = "아이템 정보 가져오기"
	MARKETWATCHER_GLYPH = "문양"
	MARKETWATCHER_GRAPH = "그래프 보기"
	MARKETWATCHER_HASBID = "입찰자 있음"
	MARKETWATCHER_HASBID2 = "입찰자 있음"
	MARKETWATCHER_HIGH = "\"고가\""
	MARKETWATCHER_HISTORY = "기록"
	MARKETWATCHER_HISTORY_OPTIONS = "기록 옵션"
	MARKETWATCHER_ITEMFOUND = "아이템 발견"
	MARKETWATCHER_ITEMNOTINBAGS = "경매장에서 아이템 정보를 확인하는 중입니다... ( %i 페이지 / 전체 %i 페이지 )"
	MARKETWATCHER_ITEMNOTINCACHE = "아이템 캐쉬에서 해당 아이템을 찾을 수 없습니다. 경매장을 검색하거나 해당 아이템의 링크를 클릭하세요."
	MARKETWATCHER_ITEMNOTINHOUSE = "경매장에서 해당아이템을 찾을 수 없습니다.  WoW database website등을 이용해 아이템ID를 사용하세요"
	MARKETWATCHER_ITEM_NOT_IN_PAGE = "%s 현재 페이지에서 찾을 수 없습니다."
	MARKETWATCHER_ITEM_REMOVED = "[기록 목록]에서 삭제됨"
	MARKETWATCHER_ITEMS_BELOW_THIS_ITEM_LEVEL = "\" 설정한 아이템 레벨보다 낮은 아이템\""
	MARKETWATCHER_ITEMS_DISPLAYED = "|cff00ffff%i|r 개의 물품표시 중 (전체물품 |cff00ffff%i|r 개)"
	MARKETWATCHER_ITEMS_I_AM_NOT_SELLING = "\" 다른 플레이어가 등록한 경매 품목\""
	MARKETWATCHER_ITEMS_I_AM_THE_LOWEST_SELLER = "\" 자신이 최저가 판매자인 아이템\""
	MARKETWATCHER_ITEMS_I_CANNOT_CRAFT_FROM_A_LACK_OF_COMPONENTS = "\" 재료 부족으로 만들 수 없는 아이템\""
	MARKETWATCHER_ITEMS_I_HAVE_BEEN_UNDERCUT = "\" 저가공급에 해당하는 아이템\\n (저가공급 : 경매최저가보다 높은 자신의 경매품)\""
	MARKETWATCHER_ITEMS_NOT_CURRENTLY_IN_MY_INVENTORY = "\" 가방에 없는 아이템\""
	MARKETWATCHER_ITEMS_SELLING_THIS_PERCENT_BELOW_HISTORICAL_AVERAGE = "\" 즉시구입 최저가가 평균 가격보다 x% 이하인 아이템\""
	MARKETWATCHER_ITEMS_THAT_HAVE_NOT_RECENTLY_SOLD = "\" 최근에 판매된 적이 없는 아이템\""
	MARKETWATCHER_ITEMS_THAT_I_CANNOT_CRAFT_WITH_MY_SELECTED_TRADESKILL = "\" 자신의 전문기술로 제작불가능한 아이템\""
	MARKETWATCHER_ITEMS_WITH_LESS_THAN_THIS_MANY_UNITS_FOR_SALE = "\" 설정한 갯수 이하로 판매중인 아이템\""
	MARKETWATCHER_ITEMS_WITH_MORE_THAN_THIS_MANY_UNITS_FOR_SALE = "\" 설정한 갯수 이상으로 판매중인 아이템\""
	MARKETWATCHER_ITEMS_WITH_NO_SAVED_SCANS_OR_TOO_FEW_SCANS_TO_DETERMINE_NA_HISTORICAL_PRICE_AVERAGE = "\" 저장된 조사기록이 없거나, 평균가격의 갯수가 적은 아이템\","
	MARKETWATCHER_ITEMS_WITH_ONE_OF_THESE_KEYWORDS_IN_THE_ITEM_NAME = "\" 아이템 이름이 아래 내용을 포함하고 있을 경우\""
	MARKETWATCHER_ITEMS_WITHOUT_A_THRESHOLD_SET = "\" 한도 설정이 없는 아이템\""
	MARKETWATCHER_ITEMS_WITHOUT_BUYOUTABLE_AUCTIONS = "\" 구매가능한 경매건수가 없는 아이템\""
	MARKETWATCHER_LAST_2_WEEKS = "\"지난 2주\""
	MARKETWATCHER_LAST_MONTH = "\"지난 달\""
	MARKETWATCHER_LAST_WEEK = "\"지난 주\""
	MARKETWATCHER_LIST = "목록 보기"
	MARKETWATCHER_LISTUPDATE1 = "경매 정보와 모든 판매자를 찾는 중입니다; 다음 질의/응답 대기중"
	MARKETWATCHER_LISTUPDATE2 = "판매자를 기다리는 중입니다."
	MARKETWATCHER_LISTUPDATE3 = "판매자를 찾았습니다., 잠시만 기다리세요"
	MARKETWATCHER_LOW = "\"저가\""
	MARKETWATCHER_LOWESTBID = " - 경매시작 최저가: %s"
	MARKETWATCHER_LOWESTBUYOUT = " - 즉시구입 최저가: %s"
	MARKETWATCHER_LOWESTBUYOUTPERUNIT = " - (최저가)개당 즉시구입가격: %s"
	MARKETWATCHER_MAX_AGE = "보유기간(일)"
	MARKETWATCHER_MAX_ENTRIES = "저장페이지 한계"
	MARKETWATCHER_MEMORY_USE = "Market Watcher v|cffffff00%s|r  메모리 사용량: |cff00ffff%.2f|r MBytes"
	MARKETWATCHER_MINING = "\"채광\""
	-- Missing translation
	-- MARKETWATCHER_MORE = "More"
	MARKETWATCHER_NOAUCTIONS = "해당 조사시간 동안  아이템에 대한 경매물건이 발견되지 않았습니다."
	MARKETWATCHER_NOBUYOUT = "|cff808080즉구가없음|r"
	MARKETWATCHER_NO_FREE_BAG_SLOT = "가방에 여유공간이 없습니다."
	MARKETWATCHER_NONE_ON_SALE = "미판매중인 아이템 표시"
	MARKETWATCHER_NONFULLSTACKAUCTIONS = "▶ 부분묶음 경매건수: |cff00ffff%i|r\\n"
	MARKETWATCHER_NONSINGLEAUCTIONS = "▶ 복수물품 경매건수: |cff00ffff%i|r\\n"
	MARKETWATCHER_NOSCANS = "해당 아이템에 대한 조사 기록이 없습니다."
	MARKETWATCHER_NOT = "\"아님\""
	MARKETWATCHER_NO_THRESHOLD = "한도 없음"
	MARKETWATCHER_NO_TRADE_SELECTED = "선택된 전문기술이 없습니다.\\n'자신의 전문기술로 제작불가능한 아이템' 필터를 사용하려면 경매창 오른쪽 하단의 전문기술을 선택해야 합니다."
	MARKETWATCHER_NOWATCHEDITEMS = "아이템 기록 목록이 비어 있습니다.이 애드온은 기록된 아이템만 조사합니다.\\n [기록 목록]탭에서 추적하고자 하는 아이템을 추가하세요"
	MARKETWATCHER_NUM_HIDDEN = " ( |cff00cccc%i|r개 아이템 필터링됨, |cff00cccc%i|r개 숨김)"
	MARKETWATCHER_NUMSCANS = "기록 페이지 ( %i 페이지 / 전체 %i 페이지)"
	MARKETWATCHER_PAGESTATUS = "해당 물품 페이지를 가져옴 |cff00ffff%i|r"
	MARKETWATCHER_PAGESTATUS2 = "해당 물품 페이지 검색 중( |cff00ffff%i|r 페이지 / 전체 |cff00ffff%i|r 페이지)"
	MARKETWATCHER_PRICE_ABOVE_THRESHOLD = "\" 한도 이상 가격\""
	MARKETWATCHER_PRICE_BELOW_THRESHOLD = "\" 한도 이하 가격\""
	MARKETWATCHER_QUERYDELAY = "쿼리 지연"
	MARKETWATCHER_QUERYSTATUS = "물품 검색 중 |cff00ffff%i|r 번째(전체: |cff00ffff%i|r)"
	MARKETWATCHER_QUERYSTATUS2 = "물품명 / 분류 : |cff1eff00%s|r / |cff00ffff%s-%s-%s%s|r"
	MARKETWATCHER_QUERYSTATUS3 = "쿼리 보냄;  응답을 기다리는 중"
	MARKETWATCHER_RECORD_CONFIRM_POPUP = "다시 조사기록을 저장하시겠습니까?\\n잦은 기록저장은 메모리를 낭비합니다.\\n저장하지 않고 조사를 하려면 [조사기록 저장]에 체크를 해제하세요."
	MARKETWATCHER_RECORDHISTORY = "조사기록 저장"
	MARKETWATCHER_RESCAN_ITEM = "아이템 재조사"
	MARKETWATCHER_R_QUALITY_ITEMS = "\"|r 품질 아이템\""
	MARKETWATCHER_SCAN = "조사"
	MARKETWATCHER_SCANCOMPLETE = "검사 완료"
	MARKETWATCHER_SCAN_RECORDED = "조사내용 기록됨 [시간 - %s]"
	MARKETWATCHER_SCANTIME = "|cff00ffff저장된 시간|r: %s (|cff00ffff%s 전|r)"
	MARKETWATCHER_SCANTIME2 = "최근 조사완료 시간 : %s (%i분 %i초 소요) (총 %i 페이지)"
	MARKETWATCHER_SELECTED_TRADESKILL = "선택된 전문기술: %s"
	MARKETWATCHER_SELL_ONE = "단품 판매"
	MARKETWATCHER_SELL_STACK = "묶음 판매"
	MARKETWATCHER_SIMPLE_MOVING_AVERAGE = "\"단순이동평균\\n(Simple Moving Average)\""
	MARKETWATCHER_SINGLEAUCTIONS = "▶ 단일물품 경매건수: |cff00ffff%i|r\\n"
	MARKETWATCHER_SKINNING = "\"무두질\""
	-- Missing translation
	-- MARKETWATCHER_SMA = "\"SMA\""
	MARKETWATCHER_SOLD = "낙찰됨 또는 경매만료"
	MARKETWATCHER_STACK_SIZE_NOT_FOUND = "해당 묶음은 발견되지 않았습니다."
	MARKETWATCHER_STACKSONLY = "최대묶음만(예:옷감 20)"
	MARKETWATCHER_SUMMARY_OPTIONS = "조사 결과 요약 옵션"
	MARKETWATCHER_TOOLTIP1 = "추적하기 위한 아이템ID.\\n 아이템ID는 WOW DB 사이트에서 얻을 수 있습니다.\\n www.wowhead.com \\n wow.inven.co.kr"
	MARKETWATCHER_TOOLTIP10 = "체크시 : |cff00ffff최대묶음 경매건수|r만 요약 \\n미체크시 : |cff00ffff단일물품/복수묶음 경매건수|r만 요약"
	MARKETWATCHER_TOOLTIP11 = "[기록 목록]의 보유기간 설정\\n  -계속 기록: 0\\n※ 보유기간 초과된 기록은 자동삭제"
	MARKETWATCHER_TOOLTIP12 = "[기록 목록] 페이지 수의 최대치\\n  - 한도 없음: 0\\n ※ 최대치초과시: 오래된 페이지 자동삭제"
	MARKETWATCHER_TOOLTIP13 = "경매물품 조사시 페이지/쿼리전송간의 지연시간을 설정합니다. 너무 낮게 설정하면 복잡한 대도시에서 접속이 종료될 수 있습니다."
	MARKETWATCHER_TOOLTIP14 = "조사기록 출력 (서버/진영/조사기록 페이지 수)"
	MARKETWATCHER_TOOLTIP15 = "경매시 [즉시구입가]를 최저가보다 낮게 설정\\n\\n (예)\\n 즉시구입 최저가 : 5골 이고\\n 즉시구입가격 인하 : 1코퍼로 설정할 경우\\n\\n자동 등록되는 즉시 구입가는 : 4골 99실 99코퍼\\n"
	MARKETWATCHER_TOOLTIP16 = "경매시 [시작가격]을 최저가보다 낮게 설정\\n\\n (예)\\n 즉시구입 최저가: 5골 이고\\n 시작가격 인하 : 10% 로 설정할 경우\\n\\n자동 등록되는 경매시작가 : 4골 49실 99코퍼\\n"
	MARKETWATCHER_TOOLTIP17 = "전문기술을 선택하세요.\\n 제작 가능한 경매 물품을 선택하면 [만들기] 버튼이 활성화 됩니다."
	MARKETWATCHER_TOOLTIP2 = "해당 아이템에 대한 조사내역을 저장하려면 체크하세요.\\n아이템을 조사시 경매장상황을 기록합니다.\\n아이템이 많거나 기록갯수가 많아지면 메모리사용량이 증가합니다."
	MARKETWATCHER_TOOLTIP3 = "체크시 : |cff00ffff최대묶음 경매건수|r만 저장 \\n미체크시 : |cff00ffff단일/복수/최대묶음 모두|r 저장"
	MARKETWATCHER_TOOLTIP4 = "체크 후 조사하면 결과를 저장합니다.\\n[조사] 버튼은 [기록 목록] 전체를 조사합니다."
	-- Missing translation
	-- MARKETWATCHER_TOOLTIP5 = "Open your tradeskill window and selected all subclasses to enable this button"
	MARKETWATCHER_TOOLTIP6 = "저가공급은 경매최저가보다 높은 자신의 경매물건입니다.\\n\\n경매를 취소하면 보증금을 잃게 됩니다.\\n\\nNote: \\n[저가공급 경매 취소]버튼은 1개의 경매만 취소합니다.\\n모두 경매취소는 블리자드에서 \\n제한했다고 제작자가 남겨놨네요."
	MARKETWATCHER_TOOLTIP7 = [=[아이템 검사 옵션을 편집하려면 우클릭

	이 아이템을 검사하려면 Shift + 우클릭

	Ctrl + Alt + Right Click will remove item if item has zero saved scans]=]
	MARKETWATCHER_MARKETWATCHER_TOOLTIP8 = "해당 아이템이 경매장에 없더라도 표시합니다."
	-- Needs review
	MARKETWATCHER_TOOLTIP9 = "※ |cff00ffff이 설정은 |r[조사]|cff00ffff탭의 최저가 색상을 변경함|r\\n※ 한도|cff00ffff는 아래|r 경매시작/즉구가 한도|cff00ffff를 의미|r\\n\\n·한도없음: |cff00ffff색상변화 없음|r\\n·한도이하/이상 물품발견시 : |cff00ffff최저가 색상변환|r\\n\\n※ 버그인지 시작가/즉구가한도를 설정하면 색상이 바뀝니다.(잘못 이해하고 있을 수도 있습니다)\\n\\n원문첨부:\\nDisplay this item only if the lowest cost is above or below the threshold price, or never hide this item when some are on sale (no threshold)"
	MARKETWATCHER_TOTALS = "총 옥션수: |cff00ffff%i|r    판매 개수: |cff00ffff%i|r"
	-- Missing translation
	-- MARKETWATCHER_TREND = "\"Trend\""
	MARKETWATCHER_TREND_LINE = "\"추세선\\n(Trend Line)\\n단기적인 변동을 무시하고 장기적인 변동을 그린 직선 또는 곡선을 말한다. 기술적 분석에서, 직선 혹은 두 개의 평행선은 증권의 움직임 방향을 나타내고 있고, 많은 분석가들은 계속 움직일 것으로 믿는다. 증권가격의 추세선이 꺽일 때 새로운 추세의 시작을 나타낸다.\\n-네이버 사전 인용\""
	MARKETWATCHER_UNHIDE = "모두 표시"
	-- Missing translation
	-- MARKETWATCHER_YOU_ARE_HIGH_BIDDER = "You are the high bidder of this auction"
	MARKETWATCHER_YOURS = "본인 등록"
end
